version: "3.9"
services:
  predictor:
    restart: always
    build:
      context: ./predictor
      dockerfile: Dockerfile.dev
    container_name: predictor
    volumes:
      - ./predictor:/app
    networks:
      - stockstalker-network

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - stockstalker-network
    depends_on:
      - predictor

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - stockstalker-network
    depends_on:
      - predictor
      - backend

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - stockstalker-network
    depends_on:
      - predictor
      - backend
      - frontend

networks:
  stockstalker-network:
    driver: bridge
