version: "3.9"
services:
  predictor:
    restart: always
    container_name: predictor
    image: index.docker.io/starlightromero/stockstalker-predictor
    networks:
      - stockstalker-network

  backend:
    restart: always
    container_name: backend
    image: index.docker.io/starlightromero/stockstalker-backend
    networks:
      - stockstalker-network
    depends_on:
      - predictor

  frontend:
    restart: always
    container_name: frontend
    image: index.docker.io/starlightromero/stockstalker-frontend
    networks:
      - stockstalker-network
    depends_on:
      - predictor
      - backend

  nginx:
    restart: always
    container_name: nginx
    image: index.docker.io/starlightromero/stockstalker-nginx
    ports:
      - 80:80
    networks:
      - stockstalker-network
    depends_on:
      - predictor
      - backend
      - frontend

networks:
  stockstalker-network:
    driver: bridge
