version: "3.9"
services:

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8100:8100
    env_file:
      - ./env/frontend.env
    networks:
      - stockstalker-network

networks:
  stockstalker-network:
    driver: bridge
