version: "3.9"
services:
  predictor:
    restart: always
    build:
      context: ./predictor
      dockerfile: Dockerfile
    container_name: predictor
    volumes:
      - ./predictor:/app
    networks:
      - stockstalker-network

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - stockstalker-network
    depends_on:
      - predictor

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - stockstalker-network
    depends_on:
      - predictor
      - backend

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - stockstalker-network
    depends_on:
      - predictor
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email starlightromero@protonmail.com --agree-tos --no-eff-email --staging -d stockstalker.tk -d www.stockstalker.tk

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/redpill/stockstalker/views/
      o: bind

networks:
  stockstalker-network:
    driver: bridge
