version: "3.9"
services:
  redis:
    container_name: cache
    image: redis:alpine
    volumes:
      - redis-data:/data/redis
    networks:
      - stockstalker-network
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    networks:
      - stockstalker-network
    depends_on:
      - redis
    command: npm test

volumes:
  redis-data:

networks:
  stockstalker-network:
    driver: bridge
