version: "3.9"
services:
  predictor:
    restart: always
    container_name: predictor
    image: index.docker.io/starlightromero/stockstalker-predictor
    networks:
      - stockstalker-network

  backend:
    restart: always
    container_name: backend
    image: index.docker.io/starlightromero/stockstalker-backend
    networks:
      - stockstalker-network
    depends_on:
      - predictor

  frontend:
    restart: always
    container_name: frontend
    image: index.docker.io/starlightromero/stockstalker-frontend
    networks:
      - stockstalker-network
    depends_on:
      - predictor
      - backend

  nginx:
    restart: always
    container_name: nginx
    image: index.docker.io/starlightromero/stockstalker-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - stockstalker-network
    depends_on:
      - predictor
      - backend
      - frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    restart: always
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  stockstalker-network:
    driver: bridge
